### ISSUE TITLE
Priority Bit Shifting of a received MCAN message 

### ISSUE THREAD

**Issue by ralflang** [bob123456678/TrainControl#1]
Hi Bob,

I am currently reading into MCAN implementations of various FOSS projects, including a lot of C and C++ based projects and now yours.
I am also (very slowly) implementing MCAN functionality into JMRI to support CS2/CS3, CanDigitalBahn components, MS2/TrackBox and possibly some other vendors' items on the bus.

What I find confusing: Most C, C++ and embedded implementations of MCAN shift the first byte right by one bit to get the priority but both JMRI and your Java implementation shift right by 4. I wonder why that is. 

See for example: https://github.com/teddych/railcontrol/blob/master/Hardware/Protocols/MaerklinCAN.h#L346

I mean, both your and their implementations work and the prio bit is not supposed to really make a difference (at least on paper).

But is shifting by 4 vs 1 a cargo where implementors looked at older code and emulated it or is there authority on what is right?

Anyway, I am very impressed by your software and I find it great that you GPLed it.

**Comment by bob123456678** [comment]
This implementation follows the Marklin specification in the document below, which states that the first 4 bits are used, with 1-4 being valid priority values.  There have been some undocumented changes with the introduction of the CS3, but for the purposes of this software this field did not seem to have any significance.  Please do share any findings to the contrary!
https://www.maerklin.de/fileadmin/media/produkte/CS2_can-protokoll_1-0.pdf

**Comment by ralflang** [comment]
There's an updated but also old document from Märklin https://streaming.maerklin.de/public-media/cs2/cs2CAN-Protokoll-2_0.pdf - It does not really differ from your protocol definition. The priority bit should not concern the receiver of the message.

Prio 1: Stopp / Go / Kurzschluss-Meldung
Prio 2: Rückmeldungen
Prio 3: Lok anhalten (?)
Prio 4: Lok / Zubehörbefehle
Rest Frei
Die Priorisierung wird von den Teilnehmern nicht als Teil der Meldung verstanden, sondern dient zum
Priorisieren der Meldung auf dem CAN Bus.

I don't have an official update beyond that but there is some research on CS2/MS2 CAN messages as of software updates here:

http://mbernstein.de/modellbahn/can/bem.htm
