### ISSUE TITLE
Getting started...

### ISSUE THREAD

**Issue by hicksan** [bob123456678/TrainControl#3]
Hi,
I am a newcomer to Java.
The readme file says to run the project using file TrainControl.jar
I cannot find this file.
It also lists 5 libraries. I found 4 in the /resources directory but not the flatlaf library.
Do I have to compile this project and if so how and with what tools?
Sorry for such basic questions.
Regards,
Andrew

**Comment by bob123456678** [comment]
Unless you plan to write custom code, there's no need to build the project (but if you did want to, the easiest way would be to import it into a new NetBeans project and build using the provided configuration).

You can download the jar file from the releases page: https://github.com/bob123456678/TrainControl/releases

**Comment by hicksan** [comment]
Perfect thanks. Might be an idea to flag the releases page in the ReadMe to deflect other newbies.

**Comment by bob123456678** [comment]
That's a great idea.  I have updated the readme!
